#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mobileIntake,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           cone,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           grabyboi,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{

  motor[mobileIntake] = 127;
  wait1Msec(3000);

	motor[cone] = -127;
	wait1Msec(800);

	motor[leftMotor] = 127;
  motor[rightMotor] = 127;
  motor[cone] = 0;
  wait1Msec(2800);

  motor[cone] = 127;
  motor[leftMotor] = 0;
  motor[rightMotor] = 0;
  wait1Msec(2000);

  motor[mobileIntake] = -127;
  wait1Msec(1000);

  motor[rightMotor] = -127;
  motor[leftMotor] = -127;
  motor[mobileIntake] = -127;
  motor[cone] = 0;
  wait1Msec(1000);

  motor[leftMotor] = -127;
  motor[rightMotor] = 127;
  motor[mobileIntake] = 0;
  wait1Msec(3000);

  motor[rightMotor] = 127;
  motor[leftMotor] = 127;
  motor[mobileIntake] = 0;
  wait1Msec(3000);

  motor[cone] = -127;
  motor[mobileIntake] = 0;
  wait1Msec(800);

  motor[rightMotor] = -127;
  motor[leftMotor] = -127;
  motor[mobileIntake] = 0;
  wait1Msec(1000);



	// ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  //AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
// User control code here, inside the loop

  while (true)
  {

  if(vexRT[Btn7U] == 1){
	 	motor[mobileIntake] = -127;
	}
	else if(vexRT[Btn7D] == 1){
		motor[mobileIntake] = 127;
	}
	else {
		motor[mobileIntake] = 0;
	}
	if(vexRT[Btn8U] == 1){
	 	motor[cone] = 127;
	}
	else if(vexRT[Btn8D] == 1){
		motor[cone] = -127;
	}
	else {
		motor[cone] = 0;
	}

	if(vexRT[Btn5U] == 1){
	 	motor[grabyboi] = 50;
	}
	else if(vexRT[Btn5D] == 1){
		motor[grabyboi] = -50;
	}
	else {
		motor[grabyboi] = 0;
	}
  	motor[rightMotor] = (vexRT[Ch3]);
  	motor[leftMotor] = (vexRT[Ch2]);

  }
}
