#pragma config(Sensor, in1,    goalHeight,     sensorPotentiometer)
#pragma config(Motor,  port1,           coneArm,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontRight,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           backLeft,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           goal,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           coneLeft,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port8,           coneLeft2,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           wristLeft,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          coneGrabber,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"

//calibrate sensors
void pre_auton()
{
	SensorValue[goalHeight] = 0;
}

//autonomous period
task autonomous()
{
	//LCD display
	displayLCDPos(0,0);
	displayNextLCDString("First Law:");
	displayLCDPos(1,0);
	displayNextLCDString("Disabled");

	//X gon give it to ya
	playSoundFile("9651xggity.wav");



}

//driver control period
task usercontrol()
{
	bLCDBacklight = true;
	string mainBattery, backupBattery;

	//threshold values
	int Y1 = 0, X1 = 0, threshold = 10;

	while(1 == 1)
	{

	/*
		//create deadzones
		if(abs(vexRT[Ch3]) > threshold)
			Y1 = vexRT[Ch3]^2/128;
		else
			Y1 = 0;
		if(abs(vexRT[Ch1]) > threshold)
			X1 = vexRT[Ch1]^2/128;
		else
			X1 = 0;

		//mecanum drive, Y1=forward/reverse, X1=turn
		motor[frontRight] = - X1 + Y1 - vexRT[Ch4];
		motor[backRight] = - X1 + Y1 + vexRT[Ch4];
		motor[frontLeft] = - X1 - Y1 - vexRT[Ch4];
		motor[backLeft] = - X1 - Y1 + vexRT[Ch4];

		*/

		//2 and 3 ch 2
		//3 and 4 ch 3

		motor[frontRight] = (vexRT[Ch2]);
		motor[backRight] = (vexRT[Ch2]);
		motor[frontLeft] = (vexRT[Ch3]);
  	motor[backLeft] = (vexRT[Ch3]);


		//mobile goal lift
		if(vexRT[Btn5D] == 1)
			{
				motor[goal] = -115;
			}
		else if(vexRT[Btn5U] == 1)
			{
				motor[goal] = 115;
			}
		else
			{
				motor[goal] = 0;
			}

		if(vexRT[Btn8U] == 1)
			{
				motor[coneArm] = -97;
			}
		else if(vexRT[Btn8D] == 1)
			{
				motor[coneArm] = 97;
			}
		else
			{
				motor[coneArm] = 0;
			}

		if(vexRT[Btn7U] == 1)
			{
				motor[coneLeft] = -127;
				motor[coneLeft2] = -127;
				motor[wristLeft] = -127;
			}
		else if(vexRT[Btn7D] == 1)
			{
				motor[coneLeft] = 127;
				motor[wristLeft] = 127;
				motor[coneLeft2] = 127;
			}
		else
			{
				motor[coneLeft] = 0;
				motor[wristLeft] = 0;
				motor[coneLeft2] = 0;
			}

		if(vexRT[Btn6U] == 1)
			{
				motor[coneGrabber] = -97;
			}
		else if(vexRT[Btn6D] == 1)
			{
				motor[coneGrabber] = 97;
			}
		else
			{
				motor[coneGrabber] = 0;
			}

	//left cone lift
	/*if(vexRT[Btn7U] == 1)
	{
	motor[coneLeft] = -127;
	motor[coneLeft2] = -127;
	}
	else if(vexRT[Btn7D] == 1)
	{
	motor[coneLeft] = 127;
	motor[coneLeft2] = 127;
	}
	else
	{
	motor[coneLeft] = 0;
	motor[coneLeft2] = 0;
	}*/

	//left wrist
	/*if(vexRT[Btn7L] == 1)
	{
	motor[wristLeft] = -127;
	}
	else if(vexRT[Btn7R] == 1)
	{
	motor[wristLeft] = 127;
	}
	else
	{
	motor[wristLeft] = 0;
	}*/

	//left claw
	/*if(vexRT[Btn6U] == 1)
	{
	motor[clawLeft] = -127;
	}
	else if(vexRT[Btn6D] == 1)
	{
	motor[clawLeft] = 127;
	}
	else
	{
	motor[clawLeft] = 0;
	}*/

	displayLCDString(0, 0, "Main: ");
	sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V');
	displayNextLCDString(mainBattery);
	displayLCDString(1, 0, "Backup: ");
	sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');
	displayNextLCDString(backupBattery);
}
}
