#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    expander_1,     sensorAnalog)
#pragma config(Sensor, dgtl1,  solenoid1,      sensorDigitalOut)
#pragma config(Sensor, dgtl2,  solenoid2,      sensorDigitalOut)
#pragma config(Motor,  port2,           driveRight,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           driveleft,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           armSegment1,   tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           armSegment2,   tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           armSegment3,   tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port7,           armSegment4,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           upperArm1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           upperArm2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightDraw,     tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


void pre_auton()
{

  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

task autonomous()
{

  AutonomousCodePlaceholderForTesting();
}



task usercontrol()
{
	bLCDBacklight = true;
  string mainBattery, backupBattery;
  while (true)
  {

  bPlaySounds = false;

  	if(vexRT[Btn8L] == 1){
		bPlaySounds = true;
		playSoundFile("car");
		playSoundFile("car.wav");
		while(bSoundActive)
		wait1Msec(1);
	}

    //Tank Controls
	motor[driveRight] = (vexRT[Ch3]);
  motor[driveLeft] = (vexRT[Ch2]);

	if(vexRT[Btn6U] == 1){
 		motor[armSegment1] = 127;
 		motor[armSegment2] = 127;
	}
	else if(vexRT[Btn6D] == 1){
		motor[armSegment1] = -127;
		motor[armSegment2] = -127;
	}
	else{
		motor[armSegment1] = 0;
		motor[armSegment2] = 0;
	}

	if(vexRT[Btn5U] == 1){
 		motor[armSegment3] = 45;
 		motor[armSegment4] = 45;
	}
	else if(vexRT[Btn5D] == 1){
		motor[armSegment3] = -45;
		motor[armSegment4] = -45;
	}
	else{
		motor[armSegment3] = 0;
		motor[armSegment4] = 0;
	}

	if(vexRT[Btn8U] == 1){
 		motor[upperArm2] = 50;
	}
	else if(vexRT[Btn8D] == 1){
 		motor[upperArm2] = -50;
	}
	else {
 		motor[upperArm2] = 0;
	}

	if(vexRT[Btn7U] == 1){
	 	motor[upperArm1] = 5;
	}
	else if(vexRT[Btn7L] == 1){
		motor[upperArm1] = -5;
	}
	else {
		motor[upperArm1] = 0;
	}

		if(vexRT[Btn7U] == 1){
	 	motor[upperArm1] = 70;
	}
	else if(vexRT[Btn7L] == 1){
		motor[upperArm1] = -70;
	}
	else {
		motor[upperArm1] = 0;
	}

	if(vexRT[Btn7R] == 1){
		motor[rightDraw] = 70;
	}
	else if(vexRT[Btn7D] == 1){
		motor[rightDraw] = -70;
	}
	else {
		motor[rightDraw] = 0;
	}


}
